// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: loser_projections.sql

package sqlc

import (
	"context"
)

const createLoserProjection = `-- name: CreateLoserProjection :exec
INSERT INTO
  LoserProjections (ProjectionData, CreatedAt)
VALUES
  (?, CURRENT_TIMESTAMP)
`

func (q *Queries) CreateLoserProjection(ctx context.Context, projectiondata string) error {
	_, err := q.db.ExecContext(ctx, createLoserProjection, projectiondata)
	return err
}

const getLatestProjection = `-- name: GetLatestProjection :one
SELECT
  ProjectionData
FROM
  LoserProjections
WHERE
  LoserProjectionID = (
    SELECT
      MAX(LoserProjectionID)
    FROM
      LoserProjections
  )
`

func (q *Queries) GetLatestProjection(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getLatestProjection)
	var projectiondata string
	err := row.Scan(&projectiondata)
	return projectiondata, err
}
