// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: loser_projections.sql

package sqlc

import (
	"context"
)

const createLoserProjection = `-- name: CreateLoserProjection :exec
INSERT INTO
  LoserProjections (ProjectionData, CreatedAt, GameStatus)
VALUES
  (?, CURRENT_TIMESTAMP, ?)
`

type CreateLoserProjectionParams struct {
	Projectiondata string
	Gamestatus     interface{}
}

func (q *Queries) CreateLoserProjection(ctx context.Context, arg CreateLoserProjectionParams) error {
	_, err := q.db.ExecContext(ctx, createLoserProjection, arg.Projectiondata, arg.Gamestatus)
	return err
}

const getLatestProjection = `-- name: GetLatestProjection :one
SELECT
  ProjectionData,
  CreatedAt,
  GameStatus
FROM
  LoserProjections
WHERE
  LoserProjectionID = (
    SELECT
      MAX(LoserProjectionID)
    FROM
      LoserProjections
  )
`

type GetLatestProjectionRow struct {
	Projectiondata string
	Createdat      string
	Gamestatus     interface{}
}

func (q *Queries) GetLatestProjection(ctx context.Context) (GetLatestProjectionRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestProjection)
	var i GetLatestProjectionRow
	err := row.Scan(&i.Projectiondata, &i.Createdat, &i.Gamestatus)
	return i, err
}
