// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Autosub struct {
	Autosubid          int64
	Leagueid           string
	Week               int64
	Playerid           string
	Substituteplayerid string
}

type Draft struct {
	Draftid   string
	Leagueid  string
	Season    string
	Type      sql.NullString
	Status    sql.NullString
	Starttime sql.NullTime
	Endtime   sql.NullTime
	Settings  sql.NullString
	Jsondata  sql.NullString
}

type Draftpick struct {
	Draftpickid int64
	Draftid     string
	Leagueid    string
	Season      string
	Round       int64
	Pick        int64
	Rostercode  int64
	Playerid    string
	Picktime    sql.NullTime
	Jsondata    sql.NullString
}

type League struct {
	Leagueid         string
	Season           string
	Name             string
	PreviousLeagueID sql.NullString
	Draftid          sql.NullString
	Status           sql.NullString
	Settings         sql.NullString
	Scoringsettings  sql.NullString
	Rosterpositions  sql.NullString
	Jsondata         sql.NullString
}

type Loserprojection struct {
	Loserprojectionid int64
	Projectiondata    string
	Createdat         string
	Gamestatus        interface{}
	Week              sql.NullInt64
	Season            sql.NullString
}

type Matchup struct {
	Matchupid    int64
	Leagueid     string
	Season       string
	Week         int64
	Matchupcode  int64
	Playoffround sql.NullInt64
	Isplayoff    sql.NullInt64
	Jsondata     sql.NullString
}

type Matchuproster struct {
	Matchuprosterid int64
	Matchupid       int64
	Rosterid        sql.NullInt64
	Rostercode      int64
	Leagueid        string
	Season          string
	Week            int64
	Points          sql.NullFloat64
	Projectedpoints sql.NullFloat64
	Iswinner        sql.NullInt64
	Jsondata        sql.NullString
}

type Matchuprosterplayer struct {
	Matchuprosterplayerid int64
	Matchuprosterid       int64
	Playerid              string
	Position              string
	Starter               int64
	Points                sql.NullFloat64
	Projectedpoints       sql.NullFloat64
	Jsondata              sql.NullString
}

type Player struct {
	Playerid     string
	Firstname    sql.NullString
	Lastname     sql.NullString
	Fullname     string
	Team         sql.NullString
	Position     string
	Status       sql.NullString
	Injurystatus sql.NullString
	Age          sql.NullInt64
	Height       sql.NullString
	Weight       sql.NullInt64
	College      sql.NullString
	Yearsexp     sql.NullInt64
	Searchrank   sql.NullInt64
	Jsondata     sql.NullString
}

type Playerhistory struct {
	Playerhistoryid int64
	Playerid        string
	Season          string
	Week            int64
	Ptshalfppr      sql.NullFloat64
}

type Projection struct {
	Projectionid  int64
	Date          sql.NullTime
	Season        string
	Week          int64
	Playerid      string
	Injurystatus  interface{}
	Pointshalfppr sql.NullFloat64
}

type Roster struct {
	Rosterid    int64
	Rostercode  int64
	Userid      sql.NullString
	Leagueid    string
	Season      string
	Teamname    sql.NullString
	Record      sql.NullString
	Streak      sql.NullString
	Fpts        sql.NullFloat64
	Fptsagainst sql.NullFloat64
	Wins        sql.NullInt64
	Losses      sql.NullInt64
	Ties        sql.NullInt64
	Jsondata    sql.NullString
}

type Seasonstat struct {
	Seasonstatsid        int64
	Rostercode           int64
	Leagueid             string
	Season               string
	Totalpoints          float64
	Totalpointsagainst   float64
	Wins                 int64
	Losses               int64
	Ties                 int64
	Winpercentage        float64
	Pointspergame        float64
	Pointsagainstpergame float64
	Pointdifferential    float64
	Regularseasonwins    int64
	Regularseasonlosses  int64
	Playoffwins          sql.NullInt64
	Playofflosses        sql.NullInt64
	Finalrank            sql.NullInt64
	Createddate          sql.NullTime
	Updateddate          sql.NullTime
}

type User struct {
	Userid      string
	Username    string
	Displayname sql.NullString
	Avatar      sql.NullString
	Jsondata    sql.NullString
}

type Weeklystat struct {
	Weeklystatsid      int64
	Rostercode         int64
	Leagueid           string
	Season             string
	Week               int64
	Points             float64
	Pointsagainst      float64
	Win                int64
	Loss               int64
	Tie                int64
	Opponentrostercode sql.NullInt64
	Isplayoff          sql.NullInt64
	Createddate        sql.NullTime
}
